
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kubeadm.bootstrap.cluster.sigs.k8s.io
  resources:
  - kubeadmbootstrapconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeadm.bootstrap.cluster.sigs.k8s.io
  resources:
  - kubeadmbootstrapconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cluster.sigs.k8s.io
  resources:
  - clusters
  - machines
  verbs:
  - get
  - list
  - watch
